#+title: gdsfeel-php2
#+author: kenjirofukuda@gmail.com
#+startup: content
#+options: ^:nil

* リポジトリ概要

lara1で学んだ成果をgdsfeel-phpと合成しながら小出し反映中

現在、PHPによる基礎クラスとユニットテストのみ(Web機能なし)

** 関連

| [[https://github.com/kenjirofukuda/gdsfeel-php][gdsfeel-php]]  | バニラPHPで書きなぐった実装     |
| [[https://github.com/kenjirofukuda/lara1][lara1]]        | laracastによるビデオ学習の追従  |


** テスト実行
#+begin_src bash
  git clone https://github.com/kenjirofukuda/gdsfeel-php2.git
  cd gdsfeel-php2/
  cp .env.example .env
  composer install
  composer dev test
#+end_src

* 移行状況
- php 実装の基礎クラスをLaravelレイアウトに準拠
- 基礎クラスのテストに着手
- 出力ファイルを storage 配下に統一
- echo によるデバッグ出力から、logger()->ベースへ移行

* 今後の予定（順未定）
- blade による画面レイアウト
- JavaScriptのモジュール化及び node ベースへの開発移行
- レイヤー管理の追加
- gdsデータのアップロード対応
- 複数ライブラリ対応

* 移行手順
** PHPクラス群
PHP実装のクラス群は、最終的に統一できると思うが現在はLaravelの自動生成クラスとの衝突による破綻を防ぐため、同一役割のクラスが2つ存在するという不自然な形をあえてとる。

=artisan make:model= にて自動生成させたクラスのインスタンス変数名、メソッド名とJSONベースのクラスの衝突状況を確認しながら、肉付けを行っていく。


合成が完了してもまだ app/gds/ 配下は削除しない。完全な削除は両方のベンチマークをとってからでも遅くはない。


*** 凡例
| app/gds/{クラス}*.php    | JSON前提のクラス群 |
| app/Models/{クラス}*.php | RDB前提のクラス群  |

*** 実例
#+begin_src
app/gds/Library.php
...
app/Models/Library.php
...
#+end_src

*  RDBに適用できるか?
データ構造が単純なRDBで置き換えられるような形式ではないためLaravel向きではない。
クライアント描画の都合上、JSON主体なのでMongoDB向きなのかもしれない。

MongoDBに移行する際は [[https://www.mongodb.com/resources/products/compatibilities/mongodb-laravel-integration][MongoDB and Laravel Integration]] を参考にすること。

Laravelそのものは、ビューの記述を簡素化させる目的で使用しても問題はないがRDBを使わない前提ならオーバースペックすぎる。

どちらにしても、Webストレージに保存してクライアント側でゴリゴリやったほうがレスポンスが良いと想定している。
どちらが速いかをみるためにも計測してみる価値はある。

* RDBにした場合(無理やり)
注）全ては網羅していない、連携の思案

**  Library

- 関連 :: Library hasMany(Structure)


| フィールド    | タイプ   | 備考                                           |
|---------------+----------+--------------------------------------------|
| id            | INTEGER  | AUTO                                       |
| name          | VARCHAR  | 内部名（ファイル名ではない）               |
| self_created  | DATETIME | 作成タイムスタンプ（レコード生成ではない） |
| self_modified | DATETIME | 修正タイムスタンプ（レコード修正ではない） |
| user_unit     | REAL     | ex. 0.001 1データベース単位の値            |
| meter_unit    | REAL     | ex. 単位 1e-9: micron                      |

**  Structure

- 関連 :: Structure hasMany(Element)

| フィールド    | タイプ   | 備考                                           |
|---------------+----------+--------------------------------------------|
| id            | INTEGER  | AUTO                                       |
| name          | VARCHAR  | ストラクチャ名                             |
| self_created  | DATETIME | 作成タイムスタンプ（レコード生成ではない） |
| self_modified | DATETIME | 修正タイムスタンプ（レコード修正ではない） |
| library_id    | INTEGER  | 所属ライブラリid                           |


**  Element

インスタンス化されるときは別々のクラスとなるが、テーブルの種類が肥大化するのを避けるため単一のテーブルにユニオン定義する。
よって、無駄なフィールドも多くなる。

- 関連 ::  hasMany(Coord)

| フィールド   | タイプ        | 備考                     |
|--------------+---------------+--------------------------|
| id           | INTEGER       | AUTO                     |
| type         | INTEGER       | Elementタイプ            |
| library_id   | INTEGER       | 所属ライブラリid         |
| structure_id | INTEGER       | 所属ストラクチャid       |
| elkey        | INTEGER       | ストラクチャ内ユニークID |
| ref_name     | VARCHAR       | SREF,AREF                |
| coods ※ 1    | TEXT or JSONB | 座標群のJSON表現         |

***  ※ 1 coods 座標群

- 候補1 :: テーブル化
- 候補2 :: coords フィールドを設けて JSON 形式で保存

**  Coord

座標

以下は
座標群の格納に、テーブル化を選択した場合

| フィールド | タイプ  | 備考         |
|------------+---------+--------------|
| id         | INTEGER | AUTO         |
| x          | REAL    |              |
| y          | REAL    |              |
| element_id | INTEGER | エレメントid |

* レイアウトの移植

既存のレイアウトを移植してみる。


- [[https://qiita.com/miki_grapes/items/89fad9241b99f35f5fa9][【Laravel】独自のCSSファイルを読み込む方法]]

* TailWindCSSを採用するとHeaderがらしく表示されない。

デフォルトの2emを上書きするデフォルトをい行っているようだ。
クセがありすぎる

** 回答
Tailwind CSSで、見出し要素（h1, h2など）のデフォルトの文字サイズがリセットされるのは、Preflightというベーススタイルが適用されているためです。 

これは、各要素が持つブラウザ独自のスタイルをなくし、デザインの一貫性と意図的なスタイリングを促すためのアプローチです。

*** デザインの一貫性を確保するため
ブラウザは、HTMLの要素（h1やulなど）にデフォルトのスタイルを適用します。しかし、このデフォルトスタイルはブラウザによって異なる場合があります。

TailwindのPreflightは、すべての要素からこれらのスタイル（文字サイズ、太字、リストの点など）をリセットし、すべてのブラウザでゼロベースの共通スタイルを適用します。これにより、予期せぬブラウザ間の表示のずれを防ぎ、どの環境でも一貫したデザインを維持しやすくなります。

*** 意図的なスタイリングを促すため
見出し要素（h1など）は、デフォルトでは大きく太字で表示されます。しかし、UI開発においては、見出し要素が必ずしも大きく強調されるべきとは限りません。 

- 意識的なデザインを促す :: 見出しのデフォルトスタイルをリセットすることで、開発者はh1やh2といった要素に意図的にtext-xlやfont-boldなどのユーティリティクラスを適用し、見た目を明示的に定義するようになります。

- 要素の役割を分ける :: これにより、HTML要素が持つ「意味」（h1は最も重要な見出し）と、「見た目」を切り離して考えることができます。 

*** デフォルトの余白が削除されるなど、他の要素もリセットされる
文字サイズだけでなく、Preflightは他のさまざまな要素のデフォルトスタイルもリセットします。

- 余白の削除 :: 見出しや段落などに適用されるデフォルトの上下マージンが削除されます。
- リストのスタイルの削除 :: <ul>や<ol>の先頭の点や数字が削除されます。
- 画像のブロックレベル化 :: <img>要素がインライン要素ではなくブロック要素として扱われ、予期せぬレイアウトの問題を防ぎます。
   
Tailwindはこのリセットによって、開発者が常に白紙の状態から独自のユーティリティクラスを組み合わせてデザインを行うことを前提としています。もしデフォルトのスタイルを保持したい場合は、Preflightを無効化することも可能です。

カラーチャート
- https://tailwindcss.com/docs/colors
- [[https://webplus8.com/laravel-blade-include-tips/][【Laravel】Bladeテンプレートでの@include活用術]]
 

* DEBUGログの抑止

DEBUGログを抑止するために
#+begin_example
LOG_CHANNEL=stack
LOG_STACK=single
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=info
#+end_example
の条件にて

#+begin_src bash
artisan serv
#+end_src
単体ではDEBUG出力されないのに

#+begin_src bash
composer run dev
#+end_src
では出力されてしまう。

内部では単に
#+begin_example
        "dev": [
            "Composer\\Config::disableProcessTimeout",
            "npx concurrently -c \"#93c5fd,#c4b5fd,#fb7185,#fdba74\" \"php artisan serve\" \"php artisan queue:listen --tries=1\" \"php artisan pail --timeout=0\" \"npm run dev\" --names=server,queue,logs,vite --kill-others"
        ],
#+end_example
servを呼び出しているにも関わらず

とりあえず、以下で抑止
#+begin_src bash
composer run --quiet dev
#+end_src

* ログの影響

#+caption: ログ有
#+begin_example
   PASS  Tests\Feature\InformTest
  ✓ singleton instance 1st                                                                          1.85s  
  ✓ singleton instance 2nd                                                                          0.93s  
#+end_example

#+caption: ログ無
#+begin_example
   PASS  Tests\Feature\InformTest
  ✓ singleton instance 1st                                                                          0.21s  
  ✓ singleton instance 2nd                                                                          0.11s  
#+end_example

#+tblname: ログ出力の付加係数
|     | no log | with log | ratio |
|-----+--------+----------+-------|
| 1st |   1.85 |     0.21 |  8.81 |
| 2nd |   0.93 |     0.11 |  8.45 |
|-----+--------+----------+-------|
|     |   1.99 |     1.91 |       |
#+TBLFM: @2$4=@2$2/@2$3;%.2f::@3$4=@3$2/@3$3;%.2f
#+TBLFM: @4$2=@2$2/@3$2;%.2f::@4$3=@2$3/@3$3;%.2f

* デバッガーの有効化

#+begin_src bash :results none :dir (file-name-directory (buffer-file-name))
composer require barryvdh/laravel-debugbar --dev
#+end_src

内部で以下のスクリプトが呼ばれているが
#+begin_example
@php artisan vendor:publish --tag=laravel-assets --ansi --force
#+end_example
ターミナル上でなくBabelなので --asciiをバイパスしたいところ
エスケープ文字列が垂れ流されてしまう。
